# rule identifiers turned on by default to exclude from running
disabled_rules:
   - trailing_whitespace
   - force_cast
   - force_unwrapping
   - force_try
   - line_length
   - identifier_name
   - empty_parentheses_with_trailing_closure
   - nesting
   
excluded:
   - Pods
